services:
  - type: web
    name: turtle-graphics-playground
    env: python
    buildCommand: pip install -r requirements_render.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT main:app
    envVars:
      - key: SESSION_SECRET
        generateValue: true